[[redirects]]
  from = "https://thelinuxterminal.com/*"
  to = "https://www.thelinuxterminal.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://thelinuxterminal.com/*"
  to = "http://www.thelinuxterminal.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.thelinuxterminal.com/*"
  to = "https://www.thelinuxterminal.com/:splat"
  status = 301
  force = true
